[package]
name = "rust_mysql_template"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
mysql = "24"
dotenvy = "0.15"
derive_more = "0.99.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
itertools = "0.13.0"
